language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --disable-external --href-ignore "#"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: dsdeiz
  - EMAIL: qwertyuiop123ph@gmail.com
  - secure: ZWfI+IADvnwQfFnh0CihSJUV6Jlsof0fxpw9CgtJhvj0Wsms+geH0KE3pEeK7IlKtmwmDifYxvHDU8dsBMLMlIbLr1Qnm6oPEoz8AXKIQr1xoblhTfgc0RPmUyAFcsA/jquXso8FM/aNJ9XygpdmAklJI1YKqbPlMzHfy+ENh+s=
