title: fr.ench.info
email: arn.french@gmail.com
description: fr.ench.info &mdash; blog about tech
baseurl: ""
url: "http://fr.ench.info"
twitter_username: breadpan
github_username:  dsdeiz
drupal_username:  dsdeiz

markdown: kramdown

permalink: /:year/:month/:day/:title/

jekyll-archives:
  enabled: [categories, tags]
  layout: archive
  permalinks:
    tag: /tag/:name/
    category: /category/:name/

exclude:
  - vendor
  - bin
  - Gemfile
  - Gemfile.lock
  - README.md
