title: fr.ench.info
email: arn.french@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://fr.ench.info"
twitter_username: breadpan
github_username:  dsdeiz

markdown: kramdown

permalink: /:year/:month/:day/:title/

jekyll-archives:
  enabled: [categories, tags]
  layout: archive
  permalinks:
    tag: /tag/:name/
    category: /category/:name/

exclude:
  - vendor
  - bin
  - Gemfile
  - Gemfile.lock
  - README.md
